version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: cargo build --verbose
      - run: cargo test --verbose
