version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - run: cargo build --verbose
      - run: cargo test --verbose
