---
name: coverage

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: rustup update

      - run: rustup component add llvm-tools-preview

      - run: cargo install grcov

      - name: Build and test for coverage
        run: |
          export CARGO_INCREMENTAL=0
          export RUSTFLAGS="-Cinstrument-coverage"
          export LLVM_PROFILE_FILE="kirunadb-%p-%m.profraw"
          cargo test

      - name: Generate lcov report
        run: |
          grcov . --binary-path ./target/debug -s . -t lcov --branch \
              --ignore src/ffi_cxx.rs --ignore-not-existing -o ./lcov.info

      - uses: codecov/codecov-action@v2
        with:
          files: ./lcov.info
